
const cartActionTypes = {
    'CART_ADDED': 'CART_ADDED',
    'CART_INCREMENTED': 'CART_INCREMENTED',
    'CART_DECREMENTED': 'CART_DECREMENTED',
    'CART_DELETED': 'CART_DELETED' ,
    'QUANTITY_CALCULATED': 'QUANTITY_CALCULATED',
    'PRICES_CALCULATED': 'PRICES_CALCULATED'
};

export default cartActionTypes;