
const cartActionTypes = {
    'CART_ADDED': 'CART_ADDED',
    'CART_INCREMENTED': 'CART_INCREMENTED',
    'CART_DECREMENTED': 'CART_DECREMENTED',
    'CART_DELETED': 'CART_DELETED',
    'STOCK_FINISHED': 'STOCK_FINISHED',
    'SHOW_POP_UP': 'SHOW_POP_UP',
    'HIDE_POP_UP': 'HIDE_POP_UP'
};

export default cartActionTypes;